import {z} from 'zod';
export const kinds=['homepage','settings','seo','sermons','events','service_times','ministries','announcements','gallery_albums','gallery_images','leadership','giving_methods','giving_campaigns','pages'] as const;
export const requiredWhenPublished:Partial<Record<(typeof kinds)[number],string[]>>={giving_methods:['bank_name','account_name','account_number','currency'],service_times:['location','day','start','end','timezone'],gallery_images:['album_slug']};
const safeUrl=z.string().max(2000).refine(x=>!x||/^https:\/\//.test(x),'Use an https:// URL');
export const contentInput=z.object({kind:z.enum(kinds),slug:z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/).max(150),title:z.string().min(1).max(180),description:z.string().max(1000),body:z.string().max(50000),external_url:safeUrl,starts_at:z.string().refine(x=>!x||!isNaN(Date.parse(x)),'Invalid date'),image_url:z.string().max(2000).regex(/^[a-zA-Z0-9/._-]*$/),image_alt:z.string().max(300),featured:z.coerce.boolean().default(false),status:z.enum(['draft','published']),display_order:z.coerce.number().int().min(0).max(10000),seo_title:z.string().max(180),seo_description:z.string().max(300),data:z.record(z.string().max(80),z.string().max(2000))}).refine(x=>!x.image_url||x.image_alt.length>0,{message:'Images need descriptive alt text'})
 .refine(x=>x.status==='draft'||(requiredWhenPublished[x.kind]||[]).every(field=>Boolean(x.data[field])),{message:'Complete every required field for this content type before publishing'})
 .refine(x=>!x.data.email||z.email().safeParse(x.data.email).success,{message:'Enter a valid public email address'})
 .refine(x=>['spotify','map_url'].every(field=>!x.data[field]||/^https:\/\//.test(x.data[field])),{message:'Links must start with https://'})
 .refine(x=>['start','end'].every(field=>!x.data[field]||/^([01]\d|2[0-3]):[0-5]\d$/.test(x.data[field])),{message:'Times use 24-hour HH:MM'})
 .refine(x=>!x.data.start||!x.data.end||x.data.start<x.data.end,{message:'A service must end after it starts'});
export const submissionInput=z.object({kind:z.enum(['contact','prayer-request','plan-your-visit','newsletter','event-interest']),name:z.string().trim().min(1).max(100),email:z.email().max(254),message:z.string().trim().min(10).max(5000),consent:z.literal('on'),website:z.string().max(0),token:z.string().max(3000)});
