backend:
  name: git-gateway
  branch: main

media_folder: "src/datalogs/images"
public_folder: "/datalogs/images"

collections:
  - name: "events"
    label: "Event Updates"
    folder: "src/datalogs/events"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
