backend:
  name: git-gateway
  branch: main

media_folder: "Gloryhills/src/datalogs/images"
public_folder: "/Gloryhills/datalogs/images"

collections:
  - name: "events"
    label: "Event Updates"
    folder: "Gloryhills/src/datalogs/events"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }

  - name: "youtube_sermons"
    label: "Youtube Sermons"
    folder: "Gloryhills/src/datalogs/y_sermons"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Youtube Link", name: "externalLink", widget: "text" }
  
  - name: "spotify_sermons"
    label: "Spotify Sermons"
    folder: "Gloryhills/src/datalogs/s_sermons"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Spotify Link", name: "externalLink", widget: "text" }
