import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {meta} from '@/lib/seo';
import {mission,published,settings} from '@/lib/content';
import about from '@/lib/content/legacy-about.json';
import PublicForm from '@/components/public-form';
import CopyAccount from '@/components/copy-account';
import {schedule} from '@/lib/fields';
import Consent from '@/components/consent';
const pages:Record<string,[string,string]>={'about-us':['Our story. His purpose.','A community committed to making disciples and building up the body of Christ.'],leadership:['Meet our pastors','Serving the church through teaching, discipleship and worship.'],sermons:['A word for your walk.','Listen, reflect and grow in the knowledge of Christ.'],events:['Life together.','Gatherings, services and opportunities to grow in faith.'],give:['A generous heart.','Support the life and ministry of Glory Hills Community Church.'],'visit-us':['There is a place for you.','We look forward to worshipping with you.'],contact:['Let’s connect.','Get in touch with the church team.'],'prayer-request':['You do not walk alone.','Share a prayer request with our pastoral team.'],'plan-your-visit':['Your first Sunday starts here.','Let us know you are coming.'],cookies:['Cookie preferences','Choose whether to allow optional analytics.'],ministries:['Find your community.','Ways to grow and serve together.'],gallery:['Our life in pictures.','Moments from our church family.']};
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const {page}=await params;const p=pages[page];const editorial=(await published('pages')).find(x=>x.slug===page);return editorial?meta(editorial.seo_title||editorial.title,editorial.seo_description||editorial.description,`/${page}`):p?meta(p[0],p[1],`/${page}`):{};}
export default async function Page({params}:{params:Promise<{page:string}>}){const {page}=await params;const p=pages[page];if(!p){const editorial=(await published('pages')).find(x=>x.slug===page);if(!editorial)notFound();return <main id="main"><header className="page-heading"><h1>{editorial.title}</h1><p>{editorial.description}</p></header><article className="content-section prose"><p>{editorial.body}</p></article></main>;}const [rows,s]=await Promise.all([published(page==='gallery'?'gallery_albums':page),settings()]);if(['ministries','gallery'].includes(page)&&!rows.length)notFound();return <main id="main"><header className="page-heading"><p className="eyebrow">GLORY HILLS COMMUNITY CHURCH</p><h1>{p[0]}</h1><p className="lead">{p[1]}</p></header><section className="content-section">
{page==='about-us'&&<div className="prose"><h2>Our mission</h2><p>{mission}</p><h2>Our vision</h2><p>Evangelizing the world, discipling the nations.</p><p>{about.vision_grid.content[0].body[2]}</p><p>Matthew 28:17–20</p><Link className="button" href="/leadership">Meet our pastors ↗</Link></div>}
{page==='leadership'&&rows.length>0&&<div className="cards">{rows.map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p>{x.description}</p><p>{x.body}</p></article>)}</div>}{page==='leadership'&&rows.length===0&&<><article className="split"><Image src="/images/leadership/pastor_tobi.webp" alt="Pastor Tobi Omojowo" width={640} height={760}/><div><p className="eyebrow">SENIOR PASTOR</p><h2>Pastor Tobi Omojowo</h2><p>{about.lead_pastor.content[0].body[0]}</p></div></article><h2 style={{marginTop:60}}>Our leadership</h2><div className="cards">{about.leadership.leadership_team.map(x=><article className="card" key={x.name}><Image src={'/images/leadership/'+x.image.split('/').pop()!.replace('.jpg','.webp')} alt={x.name} width={640} height={760}/><h3>{x.name}</h3><p>{x.title.replace('Asscoiate','Associate')}</p></article>)}</div><p>Leadership information restored from our website archive; current details are being reviewed.</p></>}
{page==='sermons'&&<><p><a className="button" href={s.spotify}>Listen to our podcast on Spotify ↗</a></p>{rows.length?<div className="cards">{rows.map(x=><article className="card" key={x.id}><h2><Link href={`/sermons/${x.slug}`}>{x.title}</Link></h2><p>{x.description}</p><Link className="text-link" href={`/sermons/${x.slug}`}>Listen ↗</Link></article>)}</div>:<><div className="notice">Our sermon library is being restored. You can still listen through these links from our archive.</div><div className="cards">{[['A message from our archive','https://youtu.be/oU_ywPEBL2Y'],['Watch a previous service','https://www.youtube.com/watch?v=xTEio7mLZ8c'],['More from our archive','https://www.youtube.com/watch?v=HsIlFfsRt4c'],['An archived service','https://www.youtube.com/watch?v=0lVoeZf9FFQ&t=3776s'],['Listen to an archived message','https://www.youtube.com/watch?v=srj86o_9PBU&t=4s']].map(([title,url])=><article className="card" key={url}><p className="eyebrow">YOUTUBE ARCHIVE</p><h2>{title}</h2><a className="button" href={url} rel="noreferrer">Listen on YouTube ↗</a></article>)}</div></>}</>}
{page==='events'&&<>{rows.filter(x=>x.starts_at&&new Date(x.starts_at)>new Date()).length?<div className="cards">{rows.filter(x=>x.starts_at&&new Date(x.starts_at)>new Date()).map(x=><article className="card" key={x.id}><h2><Link href={`/events/${x.slug}`}>{x.title}</Link></h2><p>{new Date(x.starts_at!).toLocaleString('en-GB',{timeZone:'Africa/Lagos'})} WAT</p><p>{x.description}</p></article>)}</div>:<div className="notice"><h2>Gather with us</h2><p>New event dates will appear here when confirmed.</p><Link href="/visit-us">View service information ↗</Link></div>}</>}
{page==='give'&&<><div className="prose"><h2>Giving is an expression of faith.</h2><p>Thank you for your heart to support the work of the church. Choose a church-approved giving method below when available.</p></div><Giving/><Campaigns/><div className="prose"><h2>Giving with confidence</h2><details><summary>How can I confirm the account details?</summary><p>Use only giving details published here by the church. Contact the church team if you are unsure.</p></details><details><summary>Can I give online?</summary><p>Online giving will be available once the church confirms its payment provider. We never ask for your card number or PIN through this website.</p></details><p><Link href="/contact">Contact us for giving assistance ↗</Link></p></div></>}
{page==='visit-us'&&<><Services/><div className="prose"><h2>Ojodu Berger · Headquarters</h2><p>{s.headquarters}</p><h2>Isheri Magodo</h2><p>{s.isheri}</p>{s.map_url&&/^https:\/\//.test(s.map_url)&&<a className="button" href={s.map_url}>Get directions ↗</a>}<p><Link href="/plan-your-visit">Let us know you are coming ↗</Link></p></div></>}
{['contact','prayer-request','plan-your-visit'].includes(page)&&<><div className="notice">{s.phone?<a href={`tel:${s.phone.replace(/[^+0-9]/g,'')}`}>{s.phone}</a>:'The church’s contact information is being confirmed.'}{s.email&&<p><a href={`mailto:${s.email}`}>{s.email}</a></p>}</div><PublicForm kind={page}/></>}
{page==='cookies'&&<div className="prose"><p>Essential administrator session cookies are used only when administrators sign in. Optional marketing tags stay off until you choose to allow analytics. You can change your choice here.</p><Consent/></div>}
{['ministries','gallery'].includes(page)&&(rows.length?<div className="cards">{rows.map(x=><article className="card" key={x.id}><h2>{page==='gallery'?<Link href={`/gallery/${x.slug}`}>{x.title}</Link>:x.title}</h2><p>{x.description}</p><p>{x.body}</p></article>)}</div>:<div className="notice">This collection is being restored. <Link href="/contact">Contact the church for information.</Link></div>)}
</section></main>}
async function Services(){const rows=await published('service_times');return rows.length?<div className="cards">{rows.map(x=><article className="card" key={x.id}><h2>{x.title}</h2>{x.data.location&&<p className="eyebrow">{x.data.location}</p>}{schedule(x.data)&&<p>{schedule(x.data)}</p>}<p>{x.description}</p></article>)}</div>:<div className="notice"><h2>Service times</h2><p>Ojodu Berger headquarters: Sunday 8:00 AM–1:00 PM and Wednesday 6:00 PM–8:30 PM (WAT). The Isheri Magodo schedule will be published separately when confirmed.</p></div>}
async function Giving(){const rows=await published('giving_methods');return rows.length?<div className="cards">{rows.map(x=><article className="card" key={x.id}><p className="eyebrow">{x.data.currency}</p><h2>{x.title}</h2><p>{x.data.bank_name}<br/>{x.data.account_name}</p><p>{x.data.account_number}</p>{x.data.swift&&<p>SWIFT: {x.data.swift}</p>}<CopyAccount account={x.data.account_number} category={x.title}/></article>)}</div>:<div className="notice"><h2>Giving details are being confirmed.</h2><p>Bank details and online giving will be published after the church verifies them.</p></div>}

async function Campaigns(){const rows=await published('giving_campaigns');return rows.length?<section><h2>Projects and missions</h2><div className="cards">{rows.map(x=><article className="card" key={x.id}><h3>{x.title}</h3><p>{x.description}</p><p>{x.body}</p></article>)}</div></section>:null;}
