import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('PostgreSQL RLS: published content, private drafts/submissions, admin and super-admin boundaries',async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema public,auth,storage to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated;`);
 await db.exec(await readFile('../supabase/migrations/202609150001_initial.sql','utf8'));
 await db.exec(`grant select,insert,update,delete on all tables in schema public to anon,authenticated,service_role;grant select,insert,update,delete on storage.objects to anon,authenticated;insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');insert into public.user_roles values('00000000-0000-0000-0000-000000000001','admin'),('00000000-0000-0000-0000-000000000002','super_admin');insert into content(kind,slug,title,status,published_at,image_url,image_alt) values('sermons','public','Public','published',now(),'public.jpg','Image'),('sermons','draft','Draft','draft',null,'draft.jpg','Draft image'),('sermons','future','Future','published',now()+interval '1 day',null,null);insert into submissions(kind,name,email,message) values('contact','Private name','private@example.test','Private message');insert into storage.objects(bucket_id,name) values('church-media','public.jpg'),('church-media','draft.jpg');`);
 await db.exec(`set role anon`);assert.deepEqual((await db.query('select title from content')).rows,[{title:'Public'}]);assert.equal((await db.query('select * from submissions')).rows.length,0);assert.equal((await db.query('select * from user_roles')).rows.length,0);assert.deepEqual((await db.query('select name from storage.objects')).rows,[{name:'public.jpg'}]);await assert.rejects(db.exec(`insert into content(kind,slug,title) values('sermons','bad','Bad')`));await assert.rejects(db.exec(`select public.consume_rate_limit('bypass')`));
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false)`);assert.equal((await db.query('select * from content')).rows.length,1);await assert.rejects(db.exec(`insert into user_roles values('00000000-0000-0000-0000-000000000003','super_admin')`));
 await db.exec(`select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false)`);assert.equal((await db.query('select * from content')).rows.length,3);assert.equal((await db.query('select * from submissions')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,2);await assert.rejects(db.exec(`insert into user_roles values('00000000-0000-0000-0000-000000000003','admin')`));await db.exec(`update content set status='draft' where slug='public'`);
 await db.exec(`select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false)`);await db.exec(`insert into user_roles values('00000000-0000-0000-0000-000000000003','admin')`);assert.equal((await db.query('select * from user_roles')).rows.length,3);
 await db.exec(`reset role;set role anon`);assert.equal((await db.query('select * from storage.objects')).rows.length,0);assert.equal((await db.query('select * from content')).rows.length,0);
 await db.exec(`reset role;set role service_role`);for(let i=0;i<5;i++)assert.equal((await db.query("select consume_rate_limit('test') as ok")).rows[0].ok,true);assert.equal((await db.query("select consume_rate_limit('test') as ok")).rows[0].ok,false);await db.close();
});
