import Image from 'next/image';
import Link from 'next/link';
import {mission,published} from '@/lib/content';
import {meta} from '@/lib/seo';
export const metadata=meta('Welcome home','A community committed to evangelizing the world and discipling the nations.','/');
export default async function Home(){
 const [sermons,services,homepage,announcements,ministries,albums]=await Promise.all([published('sermons'),published('service_times'),published('homepage'),published('announcements'),published('ministries'),published('gallery_albums')]);
 const home=homepage[0];
 const sections:Record<string,React.ReactNode>={
 welcome:<section className="section split"><div><p className="eyebrow">WELCOME TO GLORY HILLS</p><h2>A family of faith.<br/>A life of purpose.</h2><p className="lead">We are committed to evangelizing the world and discipling the nations.</p><p>{home?.body||mission}</p><Link className="text-link" href="/about-us">Get to know us ↗</Link></div><div className="photo-frame"><Image src="/images/home/community.webp" alt="Members of the Glory Hills congregation during worship" width={783} height={645}/><span>ONE BODY. MANY STORIES.</span></div></section>,
 sermon:<section className="section sermon-section"><div className="section-heading"><div><p className="eyebrow">GROW IN THE WORD</p><h2>Faith comes by hearing.</h2></div><Link className="text-link" href="/sermons">Explore messages ↗</Link></div><article className="feature-sermon"><span className="sermon-symbol" aria-hidden="true">↗</span><div><p className="eyebrow">{sermons[0]?'FROM OUR SERMON LIBRARY':'FROM THE ARCHIVE'}</p><h3>{sermons[0]?.title||'The zeal of the Lord’s house'}</h3><p>{sermons[0]?.description||'As believers we cannot afford to be lukewarm in our responsibilities. Let the zeal of the Lord’s house be our driving force.'}</p><Link className="button" href={sermons[0]?`/sermons/${sermons[0].slug}`:'/sermons'}>Listen to a message ↗</Link></div></article></section>,
 announcements:announcements.length>0?<section className="section"><p className="eyebrow">CHURCH FAMILY UPDATES</p><div className="cards">{announcements.map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p>{x.description}</p><p>{x.body}</p></article>)}</div></section>:null,
 ministries:ministries.length>0?<section className="section"><h2>Grow and serve.</h2><p>Find your community in the life of the church.</p><Link className="button" href="/ministries">Explore ministries ↗</Link></section>:null,
 gallery:albums.length>0?<section className="section"><h2>Life in our church family.</h2><Link className="button" href="/gallery">View Sunday pictures ↗</Link></section>:null,
 visit:<section className="section visit-callout"><p className="eyebrow">YOU ARE WELCOME HERE</p><h2>Let’s walk this<br/>journey together.</h2><Link className="button" href="/plan-your-visit">Plan your visit ↗</Link></section>,
 giving:<section className="giving-strip"><div><p className="eyebrow">A GENEROUS HEART</p><h2>Give with purpose.</h2></div><Link className="button light" href="/give">Ways to give ↗</Link></section>
 };
 const configuredOrder=home?.data.section_order?.split(',').map(x=>x.trim()).filter(x=>x in sections)||[];
 const order=[...new Set([...configuredOrder,...Object.keys(sections)])];
 return <main id="main"><section className="hero"><Image src={home?.image_url?`/api/media/${encodeURIComponent(home.image_url)}`:'/images/home/hero-desktop.webp'} unoptimized={Boolean(home?.image_url)} alt={home?.image_alt||'Worship and ministry at Glory Hills Community Church'} fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">A PEOPLE. A PURPOSE. A LIFE IN CHRIST.</p><h1>{home?.title||<>Know Him.<br/>Make Him known.</>}</h1><p>{home?.description||<>Evangelizing the world.<br className="mobile-break"/> Discipling the nations.</>}</p><div className="actions"><Link className="button" href="/sermons">Listen <span>↗</span></Link><Link className="button light" href="/give">Give <span>↗</span></Link></div></div><div className="hero-foot"><span>GLORY HILLS COMMUNITY CHURCH</span><span>SCROLL TO DISCOVER ↓</span></div></section><section className="service-strip"><span className="eyebrow">LET’S GATHER</span><p>{services[0]?.description||'Sunday 8 AM · Wednesday 6 PM · Ojodu Berger HQ'}</p><Link href="/visit-us">Service information ↗</Link></section>{order.map(key=><div key={key}>{sections[key]}</div>)}</main>;
}
